//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingHouse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TradingHouseEntities : DbContext
    {
        public TradingHouseEntities()
            : base("name=TradingHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Selling> Selling { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<AccountView> AccountView { get; set; }
        public virtual DbSet<DepartmentView> DepartmentView { get; set; }
        public virtual DbSet<ProductView> ProductView { get; set; }
        public virtual DbSet<SellingView> SellingView { get; set; }
        public virtual DbSet<WorkerView> WorkerView { get; set; }
    }
}
