//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerView
    {
        public int id { get; set; }
        public Nullable<int> id_dept { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string image { get; set; }
        public string name_dept { get; set; }
    }
}
